### ISSUE TITLE
JupyterLab integration

### ISSUE THREAD

**Issue by cccs-jc** [swan-cern/jupyter-extensions#184]
I've installed SparkMonitor and it works great inside classic notebooks. I see that the JupyterLab version is in the works. Is it supposed to be functional? I get the following error. If this is normal I'm wondering how much more work is required to make it work in JupyterLab and if this is something I could help with?

```
Spark 1.3.2

$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.4.3
qtconsole        : not installed
ipython          : 7.26.0
ipykernel        : 6.2.0
jupyter client   : 6.1.12
jupyter lab      : 2.3.2
nbconvert        : 6.1.0
ipywidgets       : not installed
nbformat         : 5.1.3
traitlets        : 5.0.5

$ cat ~/spark-3.1.2-bin-hadoop3.2/conf/spark-defaults.conf
spark.extraListeners = sparkmonitor.listener.JupyterSparkMonitorListener

# For Spark 3
spark.driver.extraClassPath = ~/miniconda3/envs/jupyterlab-ext/lib/python3.9/site-packages/sparkmonitor/listener_2.12.jar

$ jupyter labextension list
JupyterLab v2.3.2
Known labextensions:
   app dir: ~/miniconda3/envs/jupyterlab-ext/share/jupyter/lab
        @swan-cern/sparkmonitor v1.1.1  enabled  OK



ERROR JupyterSparkMonitorListener: Exception sending socket message: 
java.net.SocketException: Broken pipe (Write failed)
	at java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.base/java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:110)
	at java.base/java.net.SocketOutputStream.write(SocketOutputStream.java:150)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:233)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:312)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:316)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:153)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:251)
	at sparkmonitor.listener.JupyterSparkMonitorListener.send(CustomListener.scala:55)
	at sparkmonitor.listener.JupyterSparkMonitorListener.onJobStart(CustomListener.scala:239)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:37)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.ap
```

**Comment by krishnan-r** [comment]
Thanks for your interest in the project @cccs-jc, 

This repository only has the notebook extension with a placeholder for the lab extension. 

I am at the moment working on a rewrite using TypeScript & React on a new repository at https://github.com/swan-cern/sparkmonitor/pull/1 that supports both jupyterlab and notebook with some improvements. (it is based on the jupyterlab fork: https://github.com/itsjafer/jupyterlab-sparkmonitor by itsjafer which is published in pypi as `jupyterlab-sparkmonitor`)

The idea is to publish `sparkmonitor` to pypi from https://github.com/swan-cern/sparkmonitor with support for lab and notebook.

There's a lot of areas where you can help:
- Test it out and add your code review to https://github.com/swan-cern/sparkmonitor/pull/1

Once the PR is merged, there's more work to do in
- Implementing missing features (Spark UI proxy, pagination/better rate limiting of messages to frontend etc) 
- other improvements you can think of

**Comment by krishnan-r** [comment]
JupyterLab and notebook support is available now from https://github.com/swan-cern/sparkmonitor, or `sparkmonitor` in pypi
